const sponsorships = [
  {
    applied: 174,
    img: "https://picsum.photos/200/300?random=",
    type: "Paid",
    updated: "1 day ago",
    title: "Creascent treasure",
    followers: "5k",
  },
  {
    applied: 124,
    img: "https://picsum.photos/200/300?random=",
    type: "Barter",
    updated: "1 day ago",
    title: "Creascent treasure",
    followers: "6k",
  },
  {
    applied: 122,
    img: "https://picsum.photos/200/300?random=",
    type: "Paid",
    updated: "1 day ago",
    title: "Creascent treasure",
    followers: "5k",
  },
  {
    applied: 128,
    img: "https://picsum.photos/200/300?random=",
    type: "Barter",
    updated: "1 day ago",
    title: "Creascent treasure",
    followers: "9k",
  },
  {
    applied: 133,
    img: "https://picsum.photos/200/300?random=",
    type: "Paid",
    updated: "1 day ago",
    title: "Creascent treasure",
    followers: "4k",
  },
  {
    applied: 159,
    img: "https://picsum.photos/200/300?random=",
    type: "Barter",
    updated: "1 day ago",
    title: "Creascent treasure",
    followers: "2k",
  },
  {
    applied: 159,
    img: "https://picsum.photos/200/300?random=",
    type: "Barter",
    updated: "1 day ago",
    title: "Creascent treasure",
    followers: "2k",
  },
  {
    applied: 159,
    img: "https://picsum.photos/200/300?random=",
    type: "Barter",
    updated: "1 day ago",
    title: "Creascent treasure",
    followers: "2k",
  },
  {
    applied: 159,
    img: "https://picsum.photos/200/300?random=",
    type: "Barter",
    updated: "1 day ago",
    title: "Creascent treasure",
    followers: "2k",
  },
  {
    applied: 159,
    img: "https://picsum.photos/200/300?random=",
    type: "Barter",
    updated: "1 day ago",
    title: "Creascent treasure",
    followers: "2k",
  },
  {
    applied: 159,
    img: "https://picsum.photos/200/300?random=",
    type: "Barter",
    updated: "1 day ago",
    title: "Creascent treasure",
    followers: "2k",
  },
  {
    applied: 159,
    img: "https://picsum.photos/200/300?random=",
    type: "Barter",
    updated: "1 day ago",
    title: "Creascent treasure",
    followers: "2k",
  },
  {
    applied: 159,
    img: "https://picsum.photos/200/300?random=",
    type: "Barter",
    updated: "1 day ago",
    title: "Creascent treasure",
    followers: "2k",
  },
  {
    applied: 159,
    img: "https://picsum.photos/200/300?random=",
    type: "Barter",
    updated: "1 day ago",
    title: "Creascent treasure",
    followers: "2k",
  },
  {
    applied: 159,
    img: "https://picsum.photos/200/300?random=",
    type: "Barter",
    updated: "1 day ago",
    title: "Creascent treasure",
    followers: "2k",
  },
  {
    applied: 159,
    img: "https://picsum.photos/200/300?random=",
    type: "Barter",
    updated: "1 day ago",
    title: "Creascent treasure",
    followers: "2k",
  },
];

export default sponsorships;
